namespace: my_own_namespace
name: yandex_cloud_elk
version: 1.0.0
readme: README.md
authors:
  - Yastrebov Constantine
description: Collection with my_own_module and create_file role
license: GPL-3.0-or-later
tags:
  - netology
  - test
  - file

documentation: https://github.com/hawk0774/my_own_collection
